steps:
  - name: python
    entrypoint: python
    args:  ["-m","pip","install","--upgrade","pip"]
  - name: python
    entrypoint: python
    args: ["-m","pip","install","pipenv"]
  - name: python
    entrypoint: bash
    args: 
    - '-c'
    - |
          SET PATH=/usr/local/bin/python;%PATH%
          pipenv shell
          pipenv install pytest pandas numpy
  - name: python
    entrypoint: python
    args: ["-m","pytest","test"]
artifacts:
  objects:
    location: gs://pytest-bucket-artifact/
    paths:
      - test_log.xml
  pythonPackages:
    - repository: "https://europe-west1-python.pkg.dev/bit-bpcesi-hu6-sbx/package-store"
      paths: ["dist/*"]
  

  
